
// Classes: Helper Actions
export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST';
export const FETCH_CLASSES_ERROR = 'FETCH_CLASSES_ERROR';

// Classes: Students
export const SEARCH_CLASSES_SUCCESS = 'SEARCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_BY_STUDENT = 'FETCH_CLASSES_BY_STUDENT';
export const FETCH_CLASSES_BY_STUDENT_SUCCESS = 'FETCH_CLASSES_BY_STUDENT_SUCCESS';

// Classes: Teacher
export const FETCH_CLASSES_BY_TEACHER = 'FETCH_CLASSES_BY_TEACHER';
export const FETCH_CLASSES_BY_TEACHER_SUCCESS = 'FETCH_CLASSES_BY_TEACHER_SUCCESS';

// Students
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_ERROR = 'FETCH_STUDENTS_ERROR';
export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENT_DETAIL_SUCCESS = 'FETCH_STUDENT_DETAIL_SUCCESS';
export const FETCH_STUDENT_DETAIL_REQUEST = 'FETCH_STUDENT_DETAIL_REQUEST';
export const FETCH_STUDENT_DETAIL_ERROR = 'FETCH_STUDENT_DETAIL_ERROR';

// Protected Data
export const FETCH_PROTECTED_DATA_SUCCESS = 'FETCH_PROTECTED_DATA_SUCCESS';
export const FETCH_PROTECTED_DATA_ERROR = 'FETCH_PROTECTED_DATA_ERROR';

// Registration
export const SELECT_ROLE = 'SELECT_ROLE';

// Views
export const TOGGLE_VIEW = 'TOGGLE_VIEW';

// Misc: Auth
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
