'use strict';

//Classes
export const FETCH_CLASSES = 'FETCH_CLASSES';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST';
export const FETCH_CLASSES_ERROR = 'FETCH_CLASSES_ERROR';

//Users
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FEATCH_USERS_ERROR = 'FEATCH_USERS_ERROR';
