'use strict';

//Classes
export const FETCH_CLASSES = 'FETCH_CLASSES';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST';
export const FETCH_CLASSES_ERROR = 'FETCH_CLASSES_ERROR';

// Students
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_ERROR = 'FETCH_STUDENTS_ERROR';

// Views
export const TOGGLE_VIEW = 'TOGGLE_VIEW';
